### ISSUE TITLE
파이썬 버전이랑 루비버전이 바뀌었습니다.

### ISSUE THREAD

**Issue by kitrio** [myyrakle/billion_row_challenge#43]
https://github.com/myyrakle/billion_row_challenge/commit/17a521b5b5587182378d0caf99e9748d76d2df85

루비 예제 커밋보면 한칸 밀렸는데 
README.txt 전광판에
루비가 3.0.2 고
파이썬이 3.10.12 인거 맞죠?

**Comment by myyrakle** [comment]
실수네요
